---
title: "project_4"
author: "Ng Jia Wen"
date: "7 August 2017"
output: html_document
---
```{r}
setwd("~/School/Analytical Edge/Project")
library(mlogit) 
library(ModelMetrics)
library(glmnet)
library(caret)

safety<- read.csv('train.csv')
```
### Preprocessing
```{r}
training <- subset(safety, Task <=12)
testing <- subset(safety, Task >12)


df <- dummy.data.frame(training, names=c("segment","miles","night","gender","age","educ","region","Urb","income","ppark"), sep="_")


preProcValues <- preProcess(training[,!(colnames(training) %in% c("Ch1","Ch2","Ch3","Ch4","Choice")), drop=FALSE])

training <- model.matrix(~.,data = training[,"gender"])
testing <- model.matrix(Choice~.,data = test)

trainTransformed <- predict(preProcValues, training)
testTransformed <- predict(preProcValues, testing)

```

```{r}


















train_test <- mlogit.data(training,
                  shape ='wide',
                  choice = 'Choice',
                  sep = '',
                  id.var = 'Case')

train_test_temp <- subset(train_test[c("gender","segment","miles","night","age","educ","region","Urb","income","ppark")])

x <- cor(df[,83:162])
# summarize the correlation matrix
print(correlationMatrix)
# find attributes that are highly corrected (ideally >0.75)
x<-x[,rowSums(is.na(x))==0]
highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=0.5)
# print indexes of highly correlated attributes
print(highlyCorrelated)


train <-  mlogit.data(subset(training,Task<=12),
                  shape ='wide',
                  choice = 'Choice',
                  sep = '',
                  varying = c(4:83),
                  alt.levels = c("Ch1","Ch2","Ch3","Ch4"),id.var = 'Case')

test <-  mlogit.data(subset(safety,Task > 12),
                  shape ='wide',
                  choice = 'Choice',
                  sep = '',
                  varying = c(4:83), 
                  alt.levels = c("Ch1","Ch2","Ch3","Ch4"),
                  id.var = 'Case') 

ActualChoice <- subset(safety, Task > 12)[,"Choice"]


mixedlogitmodel2 <-  mlogit(Choice ~ 1 |segment+year+night+gender+age+educ+region+Urb+income+ppark,data = train_test)


mixedlogitpred2 <- predict(mixedlogitmodel2,newdata = testing,probability = TRUE)

mixedlogit_mll_test <-mlogLoss(ActualChoice,mixedlogitpred2)

```
```
```{r}
set.seed(10)
install.package

```


```{r}


control <- trainControl(method ='cv',savePredictions = T, classProbs = T)




## SVM
set.seed(1)
fit.svm <- train(Choice~.-Case-No-Task-Ch1-Ch2-Ch3-Ch4, data=safety, method="svmRadial", trControl=control)


```